[package]
name = "ticked_symbol_ohlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rolling_ohlc = { path = "../rolling_ohlc/" }